### ISSUE TITLE
Cannot use m directly, m.default is required

### ISSUE THREAD

**Issue by ciscoheat** [spacejack/mithril.d.ts#28]
```ts
import * as m from 'mithril'
m.render(document.body, m('h1',  'Test'))
```

Gives the following errors:

```
TS7038: A namespace-style import cannot be called or constructed, and will cause a failure at runtime.
TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{ default: Static; route: Route; mount: { (element: Element, component: ComponentTypes<any, any>)...' has no compatible call signatures.
```

using `m.default('h1', 'Test')` instead works.

**Comment by ciscoheat** [comment]
using `import m from 'mithril'` also works.

**Comment by spacejack** [comment]
This depends on your bundler setup, and yes we should add some notes about this to the readme. I believe with rollup you enable `allowSyntheticDefaultImports` in tsconfig and use `import m`. With Browserify I use `import * as m`. This is how imports worked in webpack as well but I haven't tried it recently.

What bundler are you using?

**Comment by ciscoheat** [comment]
Thanks for the info, I'm using webpack 4.8.1, with typescript 2.8.3 and the latest Mithril types. It is a bit confusing, some notes would be much appreciated even though it's not Mithrils fault!

**Comment by spacejack** [comment]
Closing as this should be addressed in the readme now.

**Comment by t3hmrman** [comment]
Hey this is still an issue, even when I follow what's in the `README` -- in particular with [rollup](https://rollupjs.org/).

Rollup doesn't plan on fixing this, given [this issue thread](https://github.com/rollup/rollup/issues/1267#issuecomment-296395734) -- neither `import * as m from 'mithril'` or `import m from 'mithril'` work.  I want to note that this *does* work if you *only* run `tsc`.

I did try the `xProxy` trick from the issue thread but Rollup will complain at you with this error:

```js
default is not exported by node_modules/mithril/mithril.js
1: import * as mithrilProxy from 'mithril';
2: var m = mithrilProxy.default || mithrilProxy;
                        ^
3: // import hack (https://github.com/rollup/rollup/issues/1267#issuecomment-296395734)
```

Right now I'm getting around this by just using mithril's minified version as an external dependency and ignoring rollup's warning

[EDIT] - I just decided to switch to [ParcelJS](https://parceljs.org) -- it works much easier, and supports most of the stuff rollup does now.
